' (c) Crown copyright 2018 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class quadrature_edge_mod::quadrature_edge_type {

  -np_xyz: integer
  -weights_xyz: real[:]  <<allocatable>>
  -points_xyz : real[::] <<allocatable>>

  +<<create>>init_quadrature( <<in>>np: integer, <<in>>horizontal_edges: logical, <<in>>vertical_edges: logical, <<in>>reference_element: reference_element, <<in>>rule: quadrature_rule ) : quadrature_edge_type
  +compute_function( <<in>>function_to_call: integer, <<in>> function_space: function_space_type, <<in>>fspace_dim: integer, <<in>>ndf: integer, <<out>>basis: real[:::] )
  +get_quadrature_proxy() : quadrature_edge_proxy_type
  +quadrature_final()
  +<<destroy>>quadrature_destructor()

}

class quadrature_edge_mod::quadrature_edge_proxy_type {
  +np_xyz: integer 
  +weights_xyz: real[:]  <<pointer>>
  +points_xyz : real[::] <<pointer>>
  +nedges: integer
}

quadrature_mod::quadrature_type <|-- quadrature_edge_mod::quadrature_edge_type
quadrature_edge_mod::quadrature_edge_proxy_type -> quadrature_edge_mod::quadrature_edge_type
